# Generated by Django 4.2.2 on 2023-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="features",
            field=models.TextField(blank=True, default="", max_length=250, null=True),
        ),
    ]
